[workspace]
members  = ["crates/*"]
resolver = "2"

    [workspace.package]
    authors    = ["magic-akari <akari.ccino@gmail.com>"]
    edition    = "2021"
    homepage   = "https://github.com/wasm-fmt/web_fmt"
    license    = "MIT"
    readme     = "README.md"
    repository = "https://github.com/wasm-fmt/web_fmt"
    version    = "0.1.5"


    [workspace.dependencies]
    biome_fmt = { path = "crates/biome_fmt", version = "0.1.5", default-features = false }

    serde              = "1.0"
    serde-wasm-bindgen = "0.6"
    serde_json         = "1.0"
    wasm-bindgen       = "0.2.90"

[profile.release]
lto       = true
opt-level = "s"
