[workspace]
members  = ["crates/*"]
resolver = "2"

    [workspace.package]
    authors    = ["magic-akari <akari.ccino@gmail.com>"]
    edition    = "2021"
    homepage   = "https://github.com/wasm-fmt/web_fmt"
    license    = "MIT"
    readme     = "README.md"
    repository = "https://github.com/wasm-fmt/web_fmt"
    version    = "0.1.8"


    [workspace.dependencies]
    biome_fmt = { path = "crates/biome_fmt", version = "0.1.8", default-features = false }
    common    = { path = "crates/common", version = "0.1.8" }
    json_fmt  = { path = "crates/json_fmt", version = "0.1.8", default-features = false }

    biome_formatter      = { version = "0.4.0" }
    biome_js_formatter   = { version = "0.4.0" }
    biome_js_parser      = { version = "0.4.0" }
    biome_js_syntax      = { version = "0.4.0" }
    biome_json_formatter = { version = "0.5.7" }
    biome_json_parser    = { version = "0.4.0" }
    biome_json_syntax    = { version = "0.4.0" }

    serde              = "1.0"
    serde-wasm-bindgen = "0.6"
    serde_json         = "1.0"
    wasm-bindgen       = "0.2.92"

[profile.release]
lto       = true
opt-level = "s"
