[workspace]
members  = ["crates/*"]
resolver = "2"

    [workspace.package]
    authors = ["magic-akari <akari.ccino@gmail.com>"]
    description = "JavaScript/TypeScript formatter powered by wasm ported from Biome"
    edition = "2021"
    homepage = "https://github.com/wasm-fmt/biome_fmt"
    keywords = [
        "wasm",
        "JavaScript",
        "TypeScript",
        "JSX",
        "TSX",
        "formatter",
        "Biome",
    ]
    license = "MIT"
    readme = "README.md"
    repository = "https://github.com/wasm-fmt/biome_fmt"
    version = "0.1.2"


    [workspace.dependencies]
    biome_formatter    = "0.4.0"
    biome_js_formatter = "0.4.0"
    biome_js_parser    = "0.4.0"
    biome_js_syntax    = "0.4.0"
    serde              = { version = "1.0" }
    serde_json         = { version = "1.0" }
    wasm-bindgen       = "0.2.90"

[profile.release]
lto       = true
opt-level = "s"
