[package]
authors.workspace    = true
description          = "a formatter for web development powered by wasm"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "web_fmt"
publish              = true
repository.workspace = true
version.workspace    = true

[dependencies]
biome_fmt          = { workspace = true, default-features = false }
malva              = { version = "0.1.4", features = ["config_serde"] }
markup_fmt         = { version = "0.3.2", features = ["config_serde"] }
serde              = { workspace = true, features = ["derive"] }
serde-wasm-bindgen = { workspace = true }
serde_json         = { workspace = true, features = ["preserve_order"] }
wasm-bindgen       = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]
