name: Publish

on:
    push:
        tags:
            - "v*"

env:
    CARGO_INCREMENTAL: 0
    CARGO_TERM_COLOR: "always"
    RUST_LOG: "off"

jobs:
    publish-npm:
        if: startsWith(github.ref, 'refs/tags/v')
        runs-on: ubuntu-latest
        permissions:
            id-token: write
        steps:
            - uses: actions/checkout@v4

            - name: Install wasm-pack
              run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

            - name: Build wasm
              run: |
                  ./crates/biome_fmt/scripts/build.sh
                  ./crates/web_fmt/scripts/build.sh

            - uses: actions/setup-node@v4
              with:
                  node-version-file: ".node-version"
                  registry-url: "https://registry.npmjs.org"

            - name: Publish biome_fmt
              working-directory: crates/biome_fmt/pkg
              run: npm publish --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish web_fmt
              working-directory: crates/web_fmt/pkg
              run: npm publish --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    publish-github:
        if: startsWith(github.ref, 'refs/tags/v')
        runs-on: ubuntu-latest
        permissions:
            packages: write
        steps:
            - uses: actions/checkout@v4

            - name: Install wasm-pack
              run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

            - name: Build wasm
              run: |
                  ./crates/biome_fmt/scripts/build.sh
                  ./crates/web_fmt/scripts/build.sh

            - uses: actions/setup-node@v4
              with:
                  node-version-file: ".node-version"
                  registry-url: "https://npm.pkg.github.com"

            - name: Publish biome_fmt
              working-directory: crates/biome_fmt/pkg
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Publish web_fmt
              working-directory: crates/web_fmt/pkg
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    publish-github-release:
        if: startsWith(github.ref, 'refs/tags/v')
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4

            - name: Install wasm-pack
              run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

            - name: Build wasm
              run: |
                  ./crates/biome_fmt/scripts/build.sh
                  ./crates/web_fmt/scripts/build.sh

            - name: Package biome_fmt
              working-directory: crates/biome_fmt/pkg
              run: npm pack

            - name: Package web_fmt
              working-directory: crates/web_fmt/pkg
              run: npm pack

            - name: Release
              uses: softprops/action-gh-release@c9b46fe7aad9f02afd89b12450b780f52dacfb2d
              with:
                  files: |
                      crates/*/pkg/*.tgz
                      crates/*/pkg/*.wasm